### ISSUE TITLE
[support] Could you give some wiki or picture about how to use the plugin?

### ISSUE THREAD

**Issue by archonwang** [zitec/redmine_blocked_reason#7]
@zitec-user ,
Could you give some wiki or picture about how to use the plugin?
Thanks.

**Comment by marius-balteanu** [comment]
Yes, we'll provide soon some screenshots.

**Comment by zcatalinz** [comment]
hello @archonwang ,
I've added a readme file.

**Comment by archonwang** [comment]
@zcatalinz , Thanks.
